# Generated by Django 5.1.7 on 2025-03-29 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prakirti_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteeringEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("planting", "Tree Planting"),
                            ("cleanup", "Cleanup"),
                            ("gardening", "Gardening"),
                            ("education", "Education"),
                        ],
                        default="planting",
                        max_length=20,
                    ),
                ),
                ("spots_total", models.PositiveIntegerField(default=20)),
                ("organizer", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("waitlisted", "Waitlisted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="prakirti_admin.volunteeringevent",
                    ),
                ),
            ],
        ),
    ]
