# Generated by Django 5.1.7 on 2025-03-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prakirti_admin", "0002_volunteeringevent_eventregistration"),
        ("prakriti_setu", "0002_user_password_alter_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name for frontend display", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="indigo",
                        help_text="Color code for frontend styling",
                        max_length=20,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="volunteeringevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("planting", "Tree Planting"),
                    ("cleanup", "Cleanup"),
                    ("gardening", "Gardening"),
                    ("education", "Education"),
                    ("disaster", "Disaster Management"),
                ],
                default="planting",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(blank=True, max_length=100)),
                ("donor_email", models.EmailField(blank=True, max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("qr_code_id", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prakriti_setu.user",
                    ),
                ),
                (
                    "donation_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="prakirti_admin.donationfield",
                    ),
                ),
            ],
        ),
    ]
