# Generated by Django 5.1.4 on 2025-03-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prakirti_admin', '0003_donationfield_alter_volunteeringevent_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('total_capacity', models.PositiveIntegerField()),
                ('available_capacity', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
