# Generated by Django 5.1.7 on 2025-03-30 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prakirti_admin", "0004_resourcecapacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="RescueTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Team contact email for notifications", max_length=254
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "specialization",
                    models.CharField(
                        help_text="Team's area of expertise", max_length=100
                    ),
                ),
                ("team_size", models.PositiveIntegerField(default=1)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("additional_location", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DisasterAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "location_details",
                    models.CharField(
                        blank=True, help_text="Sector, area or landmark", max_length=200
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_alerts",
                        to="prakirti_admin.admin",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_alerts",
                        to="prakirti_admin.rescueteam",
                    ),
                ),
            ],
        ),
    ]
