# Generated by Django 5.1.4 on 2025-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prakriti_setu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=12345678, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
    ]
